package szys;


import java.io.FileNotFoundException;
import java.util.Random;

public class Test_Number extends javax.swing.JFrame{
	static int i=0;
	static int l=0;
	public Test_Number() {
		 
		super("Myapp");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
	 @SuppressWarnings("unchecked")
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        Sure_Button = new javax.swing.JButton();
        Cancel_Button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Number = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Simplified_Chinese = new javax.swing.JLabel();
        Traditional_Chinese = new javax.swing.JLabel();
        English = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Sure_Button.setText("确定");
        Sure_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                try {
					Sure_ButtonMouseClicked(evt);
				} catch (FileNotFoundException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        Cancel_Button.setText("取消");
        Cancel_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Cancel_ButtonMouseClicked(evt);
            }
        });

        jLabel1.setText("所需习题数：");

        jLabel2.setText("（1-10之内）");

        Simplified_Chinese.setText("简");
        Simplified_Chinese.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Simplified_ChineseMouseClicked(evt);
            }
        });

        Traditional_Chinese.setText("/繁");
        Traditional_Chinese.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Traditional_ChineseMouseClicked(evt);
            }
        });

        English.setText("/English");
        English.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EnglishMouseClicked(evt);
            }
        });

        jLabel6.setText("语言：");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Simplified_Chinese)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Traditional_Chinese)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(English))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Sure_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(Cancel_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Number, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)))
                .addGap(55, 65, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Cancel_Button, Sure_Button});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(Simplified_Chinese)
                    .addComponent(Traditional_Chinese)
                    .addComponent(English)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sure_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cancel_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        
    private void Sure_ButtonMouseClicked(java.awt.event.MouseEvent evt) throws FileNotFoundException {                                         
    	if(Number.getText().matches("\\d*")){
    		Frame.hh.i = Integer.parseInt(Number.getText());
    		if(Frame.hh.i<=10&&Frame.hh.i>=1)
    		{
    			if(i>0){
	        		Frame.hs.Histroy_read();
	            	for(int a=0;a<Frame.hh.i;a++){
	            		int b = new Random().nextInt(Frame.hs.astrlist.size()-1);
	            		Frame.hh.Answer.set(a, Frame.hs.astrlist.get(b));
	            		Frame.hh.Qusetion.set(a, Frame.hs.qstrlist.get(b));
	            	}
	            	for(int a=0;a<(10-Frame.hh.i);a++){
	            		Frame.hh.Answer.set(a+Frame.hh.i, "");
	            		Frame.hh.Qusetion.set(a+Frame.hh.i, "");
	                }
            	
	        	}
	        	java.awt.EventQueue.invokeLater(new Runnable() {
	                public void run() {
	                    new Frame().setVisible(true);
	                }
	            });
	        	this.dispose();i++;
	        	try {
	    			Frame.hs.History_num();
	    		} catch (FileNotFoundException e) {
	    			// TODO Auto-generated catch block
	    			e.printStackTrace();
	    		}
    		}
        	
    	}
    	
    }                                        

    private void Cancel_ButtonMouseClicked(java.awt.event.MouseEvent evt) {                                           
    	this.dispose();
    } 
    private void Simplified_ChineseMouseClicked(java.awt.event.MouseEvent evt) {                                                
    	jLabel6.setText("语言:");
    	jLabel1.setText("所需习题数：");
    	jLabel2.setText("（1-10之内）");
    	Cancel_Button.setText("取消");
    	Sure_Button.setText("确定");
    	l=0;
    }                                               

    private void Traditional_ChineseMouseClicked(java.awt.event.MouseEvent evt) {                                                 
    	jLabel6.setText("語言:");
    	jLabel1.setText("所需習題數：");
    	jLabel2.setText("（1-10之內）");
    	Cancel_Button.setText("取消");
    	Sure_Button.setText("確定");
    	l=1;
    }                                                

    private void EnglishMouseClicked(java.awt.event.MouseEvent evt) {                                     
        jLabel6.setText("Language:");
    	jLabel1.setText("How many questions:");
    	jLabel2.setText("(1-10)");
    	Cancel_Button.setText("Cancel");
    	Sure_Button.setText("OK");
    	l=2;
    }                                    


    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify                     
    private javax.swing.JButton Cancel_Button;
    private javax.swing.JLabel English;
    private javax.swing.JTextField Number;
    private javax.swing.JLabel Simplified_Chinese;
    private javax.swing.JButton Sure_Button;
    private javax.swing.JLabel Traditional_Chinese;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration                       
}

